### ISSUE TITLE
unknown scene: 'box'

### ISSUE THREAD

**Issue by nikomatsakis** [gyng/rust-raytracer#48]
Running a fresh, recursive checkout yields this error for me:

```
lunch-box. cargo run --release sample-config.json
     Running `target/release/rust-raytracer sample-config.json`
Job started at 1465205449...
Loading scene...
unknown scene ``box''
error: Process didn't exit successfully: `target/release/rust-raytracer sample-config.json` (exit code: 1)
```

:(

**Comment by gyng** [comment]
Sorry, the scene got renamed to `cornell`, and I forgot to change the default configuration.

I've fixed it in 508f8d51a27979404db26fe323f53a35dab8fcd8, and it should work when you do a pull.

Thanks for checking the project out!
