### ISSUE TITLE
Cannot compile the project

### ISSUE THREAD

**Issue by rococtz** [gyng/rust-raytracer#50]
Hi,

I have just cloned the project, went inside and ran the command from README:
```
cargo build --release
```

I get this:
```
error[E0642]: patterns aren't allowed in methods without bodies
   --> /home/radu/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.16/src/serialize.rs:145:45
    |
145 |                                             &f_name: &str,
    |                                             ^^^^^^^

```

My rust version:
rustc 1.27.1 (5f2b325f6 2018-07-07)

**Comment by gyng** [comment]
Hey, thanks for pointing this out! Looks like newer Rust versions have broken the old version of rustc-serialize.

Some of the crates (=rustc-serialize) are really old and deprecated; this was done during earlier times of Rust. I've updated them so the project should compile now.

**Comment by rococtz** [comment]
All good now
